using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using System.Data.Sql;
using System.Data.SqlClient;
using System.Timers;
using System.Globalization;

namespace DoAnQLDatPhong.Views
{    
    public partial class TraPhong : DevExpress.XtraEditors.XtraForm
    {
        
        public TraPhong()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
           
            
        }

        private void btnTenKH_Click(object sender, EventArgs e)
        {
            frmKhachHang kh = new frmKhachHang();
            kh.ShowDialog();
        }

        private void btphieuthue_Click(object sender, EventArgs e)
        {
            frmPhieuThuePhong pnp = new frmPhieuThuePhong();
            pnp.ShowDialog();
        }

        private void simpleButton1_Click(object sender, EventArgs e)
        {
            frmDichVu dv = new frmDichVu();
            dv.ShowDialog();
        }

        private void btnThoat_Click(object sender, EventArgs e)
        {
            Close();
        }

        
    }
}